image: docker:latest

stages:
  - test
  - lint

services:
  - docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

# - apk add --no-cache docker-compose nodejs npm
before_script:
  - apk add docker-compose

test:
  stage: test
  script:
    - apk add --update nodejs npm
    - npm ci --cache .npm --prefer-offline
    - docker-compose up -d --force-recreate --build
    - chmod +x ./test-wait.sh && ./test-wait.sh
    - npm run test

eslint:
  stage: lint
  allow_failure: true
  script:
    - apk add --update npm
    - npm ci --cache .npm --prefer-offline
    - npm run lint
    - npm run lint-md

after_script:
  - docker-compose down
